chore: update git hooks

diff --git a/etc/git-hooks/checks/code-quality b/etc/git-hooks/checks/code-quality
--- a/etc/git-hooks/checks/code-quality
+++ b/etc/git-hooks/checks/code-quality
@@ -1,17 +1,13 @@
 #!/bin/bash
 
-# Check if PHPStan is installed
-which phpstan &> /dev/null && {
-  phpstan analyze || {
-    echo "PHPStan analysis failed"
+# Check if PHPStan && PHP AT are installed
+if [ -f vendor/bin/phpstan ]; then
+  vendor/bin/phpstan analyse src --quiet || {
+    echo "PHPStan analysis failed, commit aborted."
     exit 1
   }
-}
+else
+  echo "PHPStan is not installed, commit aborted."
+  exit 1
+fi
 
-# Check if PHP Architecture Testing is installed
-which phpat &> /dev/null && {
-  phpat || {
-    echo "PHP Architecture Testing analysis failed"
-    exit 1
-  }
-}
diff --git a/etc/git-hooks/checks/unit-test b/etc/git-hooks/checks/unit-test
--- a/etc/git-hooks/checks/unit-test
+++ b/etc/git-hooks/checks/unit-test
@@ -1,13 +1,12 @@
 #!/bin/bash
 
-# Check if PHPUnit is installed
-which phpunit &> /dev/null || {
-  echo "PHPUnit is not installed"
+# Check if PHPStan && PHP AT are installed
+if [ -f vendor/bin/phpunit ]; then
+  vendor/bin/phpunit || {
+    echo "PHPUnit tests failed, commit aborted."
+    exit 1
+  }
+else
+  echo "PHPUnit is not installed, commit aborted."
   exit 1
-}
-
-# Run PHPUnit tests
-phpunit || {
-  echo "PHPUnit tests failed"
-  exit 1
-}
+fi
